# Generated by Django 5.2.6 on 2025-10-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechPalsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_description', models.TextField()),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
