# Generated by Django 5.2.6 on 2025-10-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechPalsApp', '0002_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='teck_stack',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
