# Generated by Django 5.2.6 on 2025-10-03 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechPalsApp', '0003_profile_teck_stack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='teck_stack',
            new_name='tech_stack',
        ),
    ]
