# Generated by Django 5.2.6 on 2025-10-07 07:14

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechPalsApp', '0006_groupmessage_file_alter_group_group_leader_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='service',
            new_name='booking_service',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='due_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
