# Generated by Django 5.2.6 on 2025-10-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechPalsApp', '0009_category_alter_booking_booking_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
